#pragma once
// Generated from iso-codes (LGPL-2.1) zh_CN translations (CountryNames.cs)
// and the hand-maintained city table (CityNames.cs). Do not edit by hand;
// regenerate from the C# tables.
#include <string>

namespace Services::NameTables {

inline const wchar_t* LookupCountry(const std::wstring& key) {
    struct Entry { wchar_t code[3]; wchar_t name[19]; };
    static const Entry table[] = {
        {L"AD", L"安道尔"},
        {L"AE", L"阿联酋"},
        {L"AF", L"阿富汗"},
        {L"AG", L"安提瓜和巴布达"},
        {L"AI", L"安圭拉"},
        {L"AL", L"阿尔巴尼亚"},
        {L"AM", L"亚美尼亚"},
        {L"AO", L"安哥拉"},
        {L"AQ", L"南极洲"},
        {L"AR", L"阿根廷"},
        {L"AS", L"美属萨摩亚"},
        {L"AT", L"奥地利"},
        {L"AU", L"澳大利亚"},
        {L"AW", L"阿鲁巴"},
        {L"AX", L"奥兰群岛"},
        {L"AZ", L"阿塞拜疆"},
        {L"BA", L"波斯尼亚和黑塞哥维那"},
        {L"BB", L"巴巴多斯"},
        {L"BD", L"孟加拉"},
        {L"BE", L"比利时"},
        {L"BF", L"布基纳法索"},
        {L"BG", L"保加利亚"},
        {L"BH", L"巴林"},
        {L"BI", L"布隆迪"},
        {L"BJ", L"贝宁"},
        {L"BL", L"圣巴泰勒米岛"},
        {L"BM", L"百慕大"},
        {L"BN", L"文莱"},
        {L"BO", L"玻利维亚共和国"},
        {L"BQ", L"博奈尔、圣尤斯特歇斯岛和萨巴"},
        {L"BR", L"巴西"},
        {L"BS", L"巴哈马"},
        {L"BT", L"不丹"},
        {L"BV", L"布维群岛"},
        {L"BW", L"博茨瓦纳"},
        {L"BY", L"白俄罗斯"},
        {L"BZ", L"伯利兹"},
        {L"CA", L"加拿大"},
        {L"CC", L"科科斯 (基林) 群岛"},
        {L"CD", L"刚果民主共和国"},
        {L"CF", L"中非共和国"},
        {L"CG", L"刚果"},
        {L"CH", L"瑞士"},
        {L"CI", L"科特迪瓦"},
        {L"CK", L"库克群岛"},
        {L"CL", L"智利"},
        {L"CM", L"喀麦隆"},
        {L"CN", L"中国"},
        {L"CO", L"哥伦比亚"},
        {L"CR", L"哥斯达黎加"},
        {L"CU", L"古巴"},
        {L"CV", L"佛得角"},
        {L"CW", L"库拉索"},
        {L"CX", L"圣诞岛"},
        {L"CY", L"塞浦路斯"},
        {L"CZ", L"捷克"},
        {L"DE", L"德国"},
        {L"DJ", L"吉布提"},
        {L"DK", L"丹麦"},
        {L"DM", L"多米尼克"},
        {L"DO", L"多米尼加共和国"},
        {L"DZ", L"阿尔及利亚"},
        {L"EC", L"厄瓜多尔"},
        {L"EE", L"爱沙尼亚"},
        {L"EG", L"埃及"},
        {L"EH", L"西撒哈拉"},
        {L"ER", L"厄立特里亚"},
        {L"ES", L"西班牙"},
        {L"ET", L"埃塞俄比亚"},
        {L"FI", L"芬兰"},
        {L"FJ", L"斐济"},
        {L"FK", L"福克兰群岛 (马尔维纳斯)"},
        {L"FM", L"密克罗尼西亚"},
        {L"FO", L"法罗群岛"},
        {L"FR", L"法国"},
        {L"GA", L"加蓬"},
        {L"GB", L"英国"},
        {L"GD", L"格林纳达"},
        {L"GE", L"格鲁吉亚"},
        {L"GF", L"法属圭亚那"},
        {L"GG", L"根西岛"},
        {L"GH", L"加纳"},
        {L"GI", L"直布罗陀"},
        {L"GL", L"格陵兰"},
        {L"GM", L"冈比亚"},
        {L"GN", L"几内亚"},
        {L"GP", L"瓜德罗普"},
        {L"GQ", L"赤道几内亚"},
        {L"GR", L"希腊"},
        {L"GS", L"南乔治亚和南桑德韦奇群岛"},
        {L"GT", L"瓜地马拉"},
        {L"GU", L"关岛"},
        {L"GW", L"几内亚比绍"},
        {L"GY", L"圭亚那"},
        {L"HK", L"香港"},
        {L"HM", L"赫德岛与麦克唐纳群岛"},
        {L"HN", L"洪都拉斯"},
        {L"HR", L"克罗地亚"},
        {L"HT", L"海地"},
        {L"HU", L"匈牙利"},
        {L"ID", L"印度尼西亚"},
        {L"IE", L"爱尔兰"},
        {L"IL", L"以色列"},
        {L"IM", L"曼岛"},
        {L"IN", L"印度"},
        {L"IO", L"英属印度洋领地"},
        {L"IQ", L"伊拉克"},
        {L"IR", L"伊朗伊斯兰共和国"},
        {L"IS", L"冰岛"},
        {L"IT", L"意大利"},
        {L"JE", L"泽西岛"},
        {L"JM", L"牙买加"},
        {L"JO", L"约旦"},
        {L"JP", L"日本"},
        {L"KE", L"肯尼亚"},
        {L"KG", L"吉尔吉斯坦"},
        {L"KH", L"柬埔塞"},
        {L"KI", L"基里巴斯"},
        {L"KM", L"科摩罗"},
        {L"KN", L"圣基茨和尼维斯"},
        {L"KP", L"朝鲜"},
        {L"KR", L"韩国"},
        {L"KW", L"科威特"},
        {L"KY", L"开曼群岛"},
        {L"KZ", L"哈萨克斯坦"},
        {L"LA", L"老挝人民民主共和国"},
        {L"LB", L"黎巴嫩"},
        {L"LC", L"圣卢西亚"},
        {L"LI", L"列支敦士登"},
        {L"LK", L"斯里兰卡"},
        {L"LR", L"利比里亚"},
        {L"LS", L"莱索托"},
        {L"LT", L"立陶宛"},
        {L"LU", L"卢森堡"},
        {L"LV", L"拉脱维亚"},
        {L"LY", L"利比亚"},
        {L"MA", L"摩洛哥"},
        {L"MC", L"摩纳哥"},
        {L"MD", L"摩尔多瓦共和国"},
        {L"ME", L"黑山"},
        {L"MF", L"法属圣马丁"},
        {L"MG", L"马达加斯加"},
        {L"MH", L"马绍尔群岛"},
        {L"MK", L"北马其顿"},
        {L"ML", L"马里"},
        {L"MM", L"缅甸"},
        {L"MN", L"蒙古"},
        {L"MO", L"澳门"},
        {L"MP", L"北马里亚纳群岛"},
        {L"MQ", L"马提尼克"},
        {L"MR", L"毛里塔尼亚"},
        {L"MS", L"蒙特塞拉特"},
        {L"MT", L"马尔他"},
        {L"MU", L"毛里求斯"},
        {L"MV", L"马尔代夫"},
        {L"MW", L"马拉维"},
        {L"MX", L"墨西哥"},
        {L"MY", L"马来西亚"},
        {L"MZ", L"莫桑比克"},
        {L"NA", L"纳米比亚"},
        {L"NC", L"新喀里多尼亚"},
        {L"NE", L"尼日尔"},
        {L"NF", L"诺福克岛"},
        {L"NG", L"尼日利亚"},
        {L"NI", L"尼加拉瓜"},
        {L"NL", L"荷兰"},
        {L"NO", L"挪威"},
        {L"NP", L"尼泊尔"},
        {L"NR", L"瑙鲁"},
        {L"NU", L"纽埃"},
        {L"NZ", L"新西兰"},
        {L"OM", L"阿曼"},
        {L"PA", L"巴拿马"},
        {L"PE", L"秘鲁"},
        {L"PF", L"法属玻利尼西亚"},
        {L"PG", L"巴布亚新几内亚"},
        {L"PH", L"菲律宾"},
        {L"PK", L"巴基斯坦"},
        {L"PL", L"波兰"},
        {L"PM", L"圣皮埃尔和密克隆"},
        {L"PN", L"皮特凯恩"},
        {L"PR", L"波多黎各"},
        {L"PS", L"巴勒斯坦"},
        {L"PT", L"葡萄牙"},
        {L"PW", L"帕劳"},
        {L"PY", L"巴拉圭"},
        {L"QA", L"卡塔尔"},
        {L"RE", L"留尼汪"},
        {L"RO", L"罗马尼亚"},
        {L"RS", L"塞尔维亚"},
        {L"RU", L"俄罗斯"},
        {L"RW", L"卢旺达"},
        {L"SA", L"沙特阿拉伯"},
        {L"SB", L"所罗门群岛"},
        {L"SC", L"塞舌尔"},
        {L"SD", L"苏丹"},
        {L"SE", L"瑞典"},
        {L"SG", L"新加坡"},
        {L"SH", L"圣赫勒拿-阿森松-特里斯坦-达库尼亚"},
        {L"SI", L"斯洛文尼亚"},
        {L"SJ", L"斯瓦尔巴和扬马延"},
        {L"SK", L"斯洛伐克"},
        {L"SL", L"塞拉利昂"},
        {L"SM", L"圣马力诺"},
        {L"SN", L"塞内加尔"},
        {L"SO", L"索马里"},
        {L"SR", L"苏里南"},
        {L"SS", L"南苏丹"},
        {L"ST", L"圣多美和普林西比"},
        {L"SV", L"萨尔瓦多"},
        {L"SX", L"荷属圣马丁"},
        {L"SY", L"阿拉伯叙利亚共和国"},
        {L"SZ", L"斯威士兰"},
        {L"TC", L"特克斯和凯科斯群岛"},
        {L"TD", L"乍得"},
        {L"TF", L"法属南半球领地"},
        {L"TG", L"多哥"},
        {L"TH", L"泰国"},
        {L"TJ", L"塔吉克斯坦"},
        {L"TK", L"托克劳"},
        {L"TL", L"东帝汶"},
        {L"TM", L"土库曼斯坦"},
        {L"TN", L"突尼斯"},
        {L"TO", L"汤加"},
        {L"TR", L"土耳其"},
        {L"TT", L"特里尼达和多巴哥"},
        {L"TV", L"图瓦卢"},
        {L"TW", L"中国台湾省"},
        {L"TZ", L"坦桑尼亚"},
        {L"UA", L"乌克兰"},
        {L"UG", L"乌干达"},
        {L"UM", L"美国本土外小岛屿"},
        {L"US", L"美国"},
        {L"UY", L"乌拉圭"},
        {L"UZ", L"乌兹别克斯坦"},
        {L"VA", L"梵蒂冈"},
        {L"VC", L"圣文森特和格林纳丁斯"},
        {L"VE", L"委内瑞拉玻利瓦尔共和国"},
        {L"VG", L"英属维尔京群岛"},
        {L"VI", L"美属维尔京群岛"},
        {L"VN", L"越南"},
        {L"VU", L"瓦努阿图"},
        {L"WF", L"瓦利斯和富图纳"},
        {L"WS", L"萨摩亚"},
        {L"YE", L"也门"},
        {L"YT", L"马约特"},
        {L"ZA", L"南非"},
        {L"ZM", L"赞比亚"},
        {L"ZW", L"津巴布韦"},
    };
    for (auto const& e : table) if (key == e.code) return e.name;
    return nullptr;
}

// Keys are lowercased; callers must pass a lowercase key.
inline const wchar_t* LookupCityLower(const std::wstring& key) {
    struct Entry { wchar_t code[17]; wchar_t name[6]; };
    static const Entry table[] = {
        {L"tokyo", L"东京"},
        {L"osaka", L"大阪"},
        {L"seoul", L"首尔"},
        {L"incheon", L"仁川"},
        {L"busan", L"釜山"},
        {L"singapore", L"新加坡"},
        {L"hong kong", L"香港"},
        {L"taipei", L"台北"},
        {L"shanghai", L"上海"},
        {L"beijing", L"北京"},
        {L"guangzhou", L"广州"},
        {L"shenzhen", L"深圳"},
        {L"bangkok", L"曼谷"},
        {L"kuala lumpur", L"吉隆坡"},
        {L"jakarta", L"雅加达"},
        {L"manila", L"马尼拉"},
        {L"hanoi", L"河内"},
        {L"ho chi minh city", L"胡志明市"},
        {L"mumbai", L"孟买"},
        {L"new delhi", L"新德里"},
        {L"frankfurt", L"法兰克福"},
        {L"nuremberg", L"纽伦堡"},
        {L"berlin", L"柏林"},
        {L"amsterdam", L"阿姆斯特丹"},
        {L"london", L"伦敦"},
        {L"paris", L"巴黎"},
        {L"zurich", L"苏黎世"},
        {L"vienna", L"维也纳"},
        {L"madrid", L"马德里"},
        {L"barcelona", L"巴塞罗那"},
        {L"milan", L"米兰"},
        {L"rome", L"罗马"},
        {L"stockholm", L"斯德哥尔摩"},
        {L"warsaw", L"华沙"},
        {L"dublin", L"都柏林"},
        {L"istanbul", L"伊斯坦布尔"},
        {L"moscow", L"莫斯科"},
        {L"dubai", L"迪拜"},
        {L"helsinki", L"赫尔辛基"},
        {L"johannesburg", L"约翰内斯堡"},
        {L"sao paulo", L"圣保罗"},
        {L"santiago", L"圣地亚哥"},
        {L"mexico city", L"墨西哥城"},
        {L"sydney", L"悉尼"},
        {L"melbourne", L"墨尔本"},
        {L"auckland", L"奥克兰"},
        {L"new york", L"纽约"},
        {L"los angeles", L"洛杉矶"},
        {L"san jose", L"圣何塞"},
        {L"seattle", L"西雅图"},
        {L"dallas", L"达拉斯"},
        {L"chicago", L"芝加哥"},
        {L"atlanta", L"亚特兰大"},
        {L"miami", L"迈阿密"},
        {L"phoenix", L"菲尼克斯"},
        {L"vancouver", L"温哥华"},
        {L"toronto", L"多伦多"},
        {L"montreal", L"蒙特利尔"},
    };
    for (auto const& e : table) if (key == e.code) return e.name;
    return nullptr;
}

} // namespace Services::NameTables
